# -*- coding: utf-8 -*-
"""1-projeto_Lucas_Chaves_corrigido_atualizado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AFUUXZSnv99TmkU28aMev533uQdtbuj0

# **PRIMEIRO PROJETO**
## CALCULADORA
"""

primeiro_valor = int(input("Inserir primeiro valor:"))
segundo_valor = int(input("inserir segundo valor :"))
operacao = input("inserir operaçao (+, -, *, /): ")

if operacao == "+":
  resultado = primeiro_valor + segundo_valor
elif operacao == "-":
  resultado = primeiro_valor - segundo_valor
elif operacao == "*":
  resultado = primeiro_valor * segundo_valor
elif operacao == "/":
  resultado = primeiro_valor / segundo_valor
else :
  print("operacao invalida")
  exit()
print(resultado)

while True:
  continuar: str = ""

  continuar = input("Deseja continuar? (s/n)")
  if continuar == "s":
    primeiro_valor = int(input("Inserir primeiro valor:"))
    segundo_valor = int(input("inserir segundo valor :"))
    operacao = input("inserir operaçao (+, -, *, /): ")
    resultado = primeiro_valor + segundo_valor
    print(resultado)
  else:
    exit()

  if continuar == "n":
    break